### ISSUE TITLE
Add feature to process HQDM has_superclass relationship.

### ISSUE THREAD

**Issue by GCHQDeveloper42** [gchq/HQDM#1]
A feature to process HQDM `has_superclass` relationship to make type-hierarchy explicit in the host notation, such as RDFS/OWL. This would involve adding a mapping that inserts the use of `rdfs:subClassOf` property in the stored objects (an alternative could be to use the `owl:subClassOf` but this may introduce some additional issues). This may not change much in a practical sense but it would ensure that the equivalent features in the language used (RDF/RDFS/OWL) are being employed. This would also result in a RDFS/OWL binding between hqdm.owl RDFS classes and the Magma Core objects. The focus of the Magma Core work has been on internal consistency with the HQDM model itself rather than direct compatibility with the Linked Data specifications.

**Comment by twalmsley** [comment]
There is a distinction between objects that represent HQDM entity types, often referred to as the _Schema_, and objects that represent _instances_ of those types, often referred to as the _Data_.

_Schema_ objects represented as `RDF` should use `rdfs:subClassOf` to indicate the class hierarchy, but _Data_ objects should not have any `rdfs:subClassOf` predicates.

_Schema_ objects represented as Java classes, such as in this library, already include the class hierarchy in their definition in the form of the `implements` keyword, so Java Reflection can be used to traverse or determine the hierarchy in this case. 

It may be more convenient and portable to persist the HQDM _Schema_ objects into a database when it is necessary to query the _Schema_ structure.

An enhancement to the HQDM library (actually the forthcoming `HQDM-RDF` library) would include a 'Java to RDF' bidirectional mapping to allow the Java classes to be converted to and from RDF. This is explicitly *not* the same as persisting _Data_ objects. 

The model could be stored in an in-memory database since it is quite small, or alternatively it can of course be stored in a persistent database. The functionality to persist the RDF into a database naturally belongs in `MagmaCore`, while converting HQDM to and from RDF naturally belongs in `HQDM-RDF`.
