### ISSUE TITLE
Use Jena vocabulary IRI definitions for RDF & XML Schema datatypes

### ISSUE THREAD

**Issue by GCHQDeveloper42** [gchq/HQDM#6]
[Apache Jena's vocabulary package](https://github.com/apache/jena/tree/main/jena-core/src/main/java/org/apache/jena/vocabulary) defines Linked Data IRI constants for known established vocabularies including RDF(S) and XML Schema (XSD). Instead of manually defining these in `iri/RDFS.java` for use in `HQDM`, using Jena's definitions would be more effective, and also offers the use of other LD vocabularies recognised by Jena, should they be needed.

**Comment by twalmsley** [comment]
I would suggest not tying HQDM to Apache Jena any more than it already is. In fact I would prefer HQDM to be independent of Jena entirely, and a separate mapping library used instead. This will allow other storage mechanisms to be used in place of Jena and Fuseki, for example a custom service with embedded TDB instances rather than a SPARQL interface is likely to perform much better than Fuseki.

**Comment by twalmsley** [comment]
There are some PRs that isolate HQDM from Jena and RDF-specific code that make this issue redundant.
A new repo `HQDM-RDF` will specify its own constants so that it doesn't depend on any Jena libraries and can be used independently of Jena. Please review and close if you agree.
